on:
  release:
    types:
      - created

name: Deploy to CDN

jobs:
  deploy:
    name: Deploy to CDN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Copy files to CDN
        run: aws s3 sync dist "s3://${{ vars.S3_BUCKET }}/${{ github.event.repository.name }}/${{ github.ref_name }}" --cache-control "max-age=365000000, no-transform, immutable"
